### ISSUE TITLE
error: http error: API key is not valid (401)

### ISSUE THREAD

**Issue by nyl9488** [ELTCOIN/eltwallet#125]
Not able to run the application on the ios simulator
` react-native run-ios`

**Already fill in the api key in .env**

![screen shot 2018-04-25 at 12 19 57 am](https://user-images.githubusercontent.com/12860854/39200377-98cfec82-481e-11e8-901a-5d4227c7d18c.png)

**Comment by vfaramond** [comment]
I've just removed Sentry native integration in https://github.com/ELTCOIN/eltwallet/commit/dedccd54ff97604b0b836f627834c523cf9e74fb 😉
