### ISSUE TITLE
How can send ERC20 token without setting up gas?

### ISSUE THREAD

**Issue by AntonioCatanese** [ELTCOIN/eltwallet#127]
I downloaded android app, If I send any ERC20 token, it will not ask gas?
Are you sure you can send any ERC20 token between 2 ethereum wallet addresses ( from my ELT wallet app to any other address) ?
Thank you.

**Comment by vfaramond** [comment]
Hey @AntonioCatanese, gas value and gas price are determined automatically based on the network state, so you still need some ETH in your wallet but we chose not to ask the user for these values! Hope it answers your question 👍

**Comment by AntonioCatanese** [comment]
Ok  Thank you for letting me know. 
I want to make sure followings:
1) so I can send and receive real ERC20 token in mainnet ? 
2) I installed ios app on my phone, but it seems much different with demo screen. 
This source did not compile IOS version?

**Comment by vfaramond** [comment]
1. Yes, you can send ETH and ERC20 tokens on the mainnet. We even added a `Switch network` feature to use the app on Ropsten, Kovan and Rinkeby testnets 😃 

2. We have an issue with our App Store submission (the wallet is tight to a coin, Eltcoin in this case, and they don't like it), so we may rebrand the wallet in the coming weeks. For the time being, you can request a Testflight invite [here](https://eltwallet.eltcoin.tech/)

You can find the source to our previous iOS wallet [here](https://github.com/ELTCOIN/ios-wallet)

3. I've just added a license to the repository, thanks for the reminder! 😉

**Comment by AntonioCatanese** [comment]
Current App store's IOS UI seems not good, even buttons not working well.
but Google store's Nice. 
Right now I will try to use this app on my android, and following you now, once this app come up on app store, then I will use it also. 😀  
How about to compile this app' ios version with Expo?  
But I am not an expert in React Native and Expo. 😢
Thank you very much.

**Comment by vfaramond** [comment]
Yes, the old version is not maintained anymore.

You can use the new iOS version through Testflight (https://eltwallet.eltcoin.tech/)

**Comment by Aurelyn10** [comment]
Hey Antonio I also love this app and new in React Native but heard that Expo is easy to build ios app.
I will try to build Expo version of this source, but not sure I can go to end 😀
vfaramond could you help me if I am having trouble to create Expo version of this source?
Regards,
Aurelyan.

**Comment by vfaramond** [comment]
I've started the project as a Expo app but it's not possible to use NodeJS crypto api to generate a Ethereum wallet (see https://expo.canny.io/feature-requests/p/crypto-api).

And I'm not a fan of detaching to Expokit 😋

**Comment by Aurelyn10** [comment]
Ok that is very important part of your app.  I will wait for good Expo version.
For now, I will leave from Expo and try to compile IOS version with sentry integration.
Thank you.

**Comment by Aurelyn10** [comment]
And in my personal opinion, I would like to have gas select UI in this app. because other famous token wallets have the feature.

**Comment by AntonioCatanese** [comment]
Agree, I think we do not need to waste time for Expokit.
https://github.com/react-community/create-react-native-app/issues/516
I can not trust 100% of @Evanbacon's conclusion, but It is true to have trouble for using node modules in Expokit project.
