### ISSUE TITLE
IOS is crashing on simulator with error.

### ISSUE THREAD

**Issue by Aurelyn10** [ELTCOIN/eltwallet#132]
Without any change, simply I run xcode project on iphone6S simulator, but it is crashing with following error logs.

2018-04-26 20:01:18.532 [fatal][tid:main] No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
2018-04-26 20:01:18.532173+0800 eltwallet[39423:412013] No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
2018-04-26 20:01:18.542386+0800 eltwallet[39423:412389] [] nw_connection_get_connected_socket 2 Connection has no connected handler

Looking forwards the solution.
Thank you in advance.

**Comment by Aurelyn10** [comment]
Above problem, it was fixed when I add following contents to info.plist.
**<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>**
But next time, it shows sentry relation error, right now I thought to use current sentry setting without any change.
This is stupid question, but when I need to change sentry setting, how do I do?  
I would like to know detail steps for sentry setting.

![screenshot at apr 26 20-26-23](https://user-images.githubusercontent.com/35254636/39305887-3857cc70-4991-11e8-863a-45c726846799.png)

**Comment by vfaramond** [comment]
For the first solution, good catch I've committed the change to `info.plist` after a release probably, will revert it.

And for Sentry you have to edit the two files `ios/sentry.properties` and `android/sentry.properties`, I will push a commit with working credentials so nobody will run in the same troubles again 👍

**Comment by vfaramond** [comment]
Alright I've just pushed a change to master, I've completely removed Sentry for the native code! 😃

**Comment by Aurelyn10** [comment]
Thank you 👍
