### ISSUE TITLE
What is the meaning of this log, It always appears continuously. 

### ISSUE THREAD

**Issue by Aurelyn10** [ELTCOIN/eltwallet#133]
While I am running the app on iphone simulator, It shows following log continuously.

> `2018-04-27 09:14:16.641055+0800 eltwallet[4352:64030] [] nw_connection_get_connected_socket 443 Connection has no connected handler`

Where this come up?
What will affect to the app work?
Thank you.

![screenshot at apr 27 09-24-02](https://user-images.githubusercontent.com/35254636/39339720-de40842c-49fc-11e8-9f5d-80a4bb0ba6f1.png)

**Comment by vfaramond** [comment]
This is a RN issue, see https://github.com/facebook/react-native/issues/10027

**Comment by Aurelyn10** [comment]
Ok  Thank you. 😄
