### ISSUE TITLE
Iphone scale is wired on the simulators.

### ISSUE THREAD

**Issue by Aurelyn10** [ELTCOIN/eltwallet#134]
I  am not sure this is from simulator problem, but it does not fill all screen.
I  will attach the iphone X and iphone 8 screen, but iphone 7 is same problem.

![iphone x](https://user-images.githubusercontent.com/35254636/39346243-a35f7dc2-4a1f-11e8-994b-1ddee666a357.png)
![iphone8](https://user-images.githubusercontent.com/35254636/39346244-a3b98b50-4a1f-11e8-8950-bfc1d6e2488d.png)

**Comment by vfaramond** [comment]
I don't think it's related to this project and I've never experienced this issue before, maybe these two posts can help:
- https://stackoverflow.com/questions/12439778/fitting-the-iphone-5-simulator-on-my-screen
- https://stackoverflow.com/questions/31769609/how-to-fit-the-screen-to-the-window-in-ios-simulator

**Comment by Aurelyn10** [comment]
Ok thank you. 😄
