### ISSUE TITLE
failed to load bundle localhost

### ISSUE THREAD

**Issue by johndpope** [ELTCOIN/eltwallet#140]
![screen shot 2018-05-03 at 15 37 16](https://user-images.githubusercontent.com/289994/39598858-f5f44ffa-4ee7-11e8-9b70-638cceeb5571.png)
![screen shot 2018-05-03 at 15 38 12](https://user-images.githubusercontent.com/289994/39598877-07a75f44-4ee8-11e8-95a7-eeb142e9cafc.png)

![screen shot 2018-05-03 at 15 42 27](https://user-images.githubusercontent.com/289994/39599079-9dda7a00-4ee8-11e8-9357-ad518259c0c3.png)

nvm --version
0.33.11
node -v
v8.11.1
any ideas?

**Comment by vfaramond** [comment]
Hey @johndpope, do you have the output of the terminal running Metro Bundler? It's probably a JS error happening during the JS bundle build!

**Comment by johndpope** [comment]
fyi - all good. 
<img width="965" alt="screen shot 2018-08-20 at 10 51 50 am" src="https://user-images.githubusercontent.com/289994/44347909-0fe43180-a467-11e8-813a-8ecc60d4be67.png">
