### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by spectracoin** [ELTCOIN/eltwallet#18]
When I try to run the APP in Android I get the following error:

![image](https://user-images.githubusercontent.com/35724459/35563658-b630de20-05b7-11e8-89b3-3b30a918b0d8.png)

**Comment by spectracoin** [comment]
Thank you very much for your reply.

I have verified "Android_Home" is correctly implemented.

What else could it be?. I have already updated all the Android Studio Tools.

![image](https://user-images.githubusercontent.com/35724459/35611678-1927ef88-0666-11e8-992f-78843fa9aa03.png)

**Comment by vfaramond** [comment]
You can try to build the project directly in Android Studio to see if you have some warnings/errors!

**Comment by spectracoin** [comment]
It also gives me a mistake in the same part

![image](https://user-images.githubusercontent.com/35724459/35621383-711bec80-0684-11e8-8a9c-b65d56a86fe7.png)
