### ISSUE TITLE
There is the functionality for Private Key QR code output ?

### ISSUE THREAD

**Issue by AntonioCatanese** [ELTCOIN/eltwallet#197]
In this source, there seems not output of QR code for private key.
And when click share button, it shows only private key string.
But there is only option to recover wallet with private key QR code.
How do I think about this?
This source can send and receive any ERC20 token and ETH?

**Comment by vfaramond** [comment]
Hey @AntonioCatanese, thanks for your interested in Eltwallet!

True we've decided to do not display a QR code for the private key but it can easily be added in the future if we decide to.

And when you import an existing wallet you also have the possibility to enter it or paste in in the text input 👍 

And yes the wallet supports sending and receiving ETH and all ERC20 tokens
