### ISSUE TITLE
Cannot run iOS

### ISSUE THREAD

**Issue by Narsiss** [ELTCOIN/eltwallet#3]
Installing build/Build/Products/Debug-iphonesimulator/eltwallet.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/eltwallet.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by Narsiss** [comment]
![image](https://user-images.githubusercontent.com/5062214/35031937-f4650dd2-fb9f-11e7-9d63-3150413851c7.png)
![10371516176165_ pic](https://user-images.githubusercontent.com/5062214/35031943-faec3cc0-fb9f-11e7-9ff4-30a82e147484.jpg)

**Comment by Narsiss** [comment]
please help , thanks

**Comment by vfaramond** [comment]
Hey there, thanks for your interest in our project!

Make sure to pull the last changes on the `master` branch and to have the latest version of `react-native-cli` installed 👍
